"""Abstract base classes defining the registry interfaces."""

import uuid
from abc import ABC, abstractmethod
from typing import List, Optional

from shared.models.application_record import ApplicationRecord
from shared.models.job_record import JobRecord
from shared.models.variant_record import VariantRecord


class JobRegistryBase(ABC):
    """Interface for all JobRecord storage backends."""

    @abstractmethod
    async def save(self, jobs: List[JobRecord]) -> None:
        """Persist a list of job records.

        Args:
            jobs: List of JobRecord instances to save.
        """

    @abstractmethod
    async def get(self, job_id: uuid.UUID) -> JobRecord:
        """Retrieve a single job by ID.

        Args:
            job_id: UUID of the job to retrieve.

        Returns:
            The matching JobRecord.

        Raises:
            JobNotFoundError: If no job with that ID exists.
        """

    @abstractmethod
    async def get_many(self, job_ids: List[uuid.UUID]) -> List[JobRecord]:
        """Retrieve multiple jobs by their IDs.

        Args:
            job_ids: List of UUIDs to retrieve.

        Returns:
            List of matching JobRecord instances (missing IDs are skipped).
        """

    @abstractmethod
    async def get_all_with_email(self) -> List[JobRecord]:
        """Return all jobs that have a non-null apply_email.

        Returns:
            List of JobRecord instances with apply_email set.
        """

    @abstractmethod
    async def get_by_source(self, source: str) -> List[JobRecord]:
        """Return all jobs from a specific source platform.

        Args:
            source: One of "linkedin", "naukri", "indeed".

        Returns:
            List of matching JobRecord instances.
        """

    @abstractmethod
    async def get_by_status(self, status: str) -> List[JobRecord]:
        """Return all jobs with a specific status.

        Args:
            status: One of "raw", "reviewed", "applied", "closed".

        Returns:
            List of matching JobRecord instances.
        """

    @abstractmethod
    async def exists(self, job_id: uuid.UUID) -> bool:
        """Check whether a job exists without loading the full record.

        Args:
            job_id: UUID to check.

        Returns:
            True if the job exists, False otherwise.
        """

    @abstractmethod
    async def count(self) -> int:
        """Return the total number of stored jobs.

        Returns:
            Integer count of all job records.
        """

    @abstractmethod
    async def delete_by_source(self, source: str) -> int:
        """Delete all jobs from a specific source.

        Args:
            source: One of "linkedin", "naukri", "indeed".

        Returns:
            Number of records deleted.
        """


class VariantRegistryBase(ABC):
    """Interface for all VariantRecord storage backends."""

    @abstractmethod
    async def save(self, variant: VariantRecord) -> None:
        """Persist a new variant record.

        Args:
            variant: VariantRecord instance to save.
        """

    @abstractmethod
    async def get(self, variant_id: uuid.UUID) -> VariantRecord:
        """Retrieve a single variant by ID.

        Args:
            variant_id: UUID of the variant to retrieve.

        Returns:
            The matching VariantRecord.

        Raises:
            VariantNotFoundError: If no variant with that ID exists.
        """

    @abstractmethod
    async def get_for_job(self, job_id: uuid.UUID) -> List[VariantRecord]:
        """Return all variants generated for a specific job.

        Args:
            job_id: UUID of the job.

        Returns:
            List of VariantRecord instances for that job.
        """

    @abstractmethod
    async def get_approved_for_job(
        self, job_id: uuid.UUID, user_id: str
    ) -> Optional[VariantRecord]:
        """Return the approved variant for a user+job pair.

        Args:
            job_id: UUID of the job.
            user_id: Identifier of the user.

        Returns:
            The approved VariantRecord, or None if none exists.
        """

    @abstractmethod
    async def get_for_user(self, user_id: str) -> List[VariantRecord]:
        """Return all variants generated by a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            List of VariantRecord instances for that user.
        """

    @abstractmethod
    async def get_pending_for_user(self, user_id: str) -> List[VariantRecord]:
        """Return only pending variants awaiting approval for a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            List of pending VariantRecord instances.
        """

    @abstractmethod
    async def update_approval_status(self, variant_id: uuid.UUID, status: str) -> None:
        """Update the approval status of a variant.

        Args:
            variant_id: UUID of the variant to update.
            status: New status — "approved", "rejected", or "pending".
        """

    @abstractmethod
    async def update_approval_token(self, variant_id: uuid.UUID, token: str) -> None:
        """Store the email-based approval token for a variant.

        Args:
            variant_id: UUID of the variant.
            token: 64-character hex approval token.
        """

    @abstractmethod
    async def exists(self, variant_id: uuid.UUID) -> bool:
        """Check whether a variant exists.

        Args:
            variant_id: UUID to check.

        Returns:
            True if the variant exists, False otherwise.
        """

    @abstractmethod
    async def count_by_user(self, user_id: str) -> int:
        """Count variants generated by a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            Integer count of variants for that user.
        """


class ApplicationLogBase(ABC):
    """Interface for all ApplicationRecord storage backends."""

    @abstractmethod
    async def record_send(self, record: ApplicationRecord) -> None:
        """Log a new application send.

        Args:
            record: ApplicationRecord to persist.
        """

    @abstractmethod
    async def get(self, application_id: uuid.UUID) -> ApplicationRecord:
        """Retrieve an application by ID.

        Args:
            application_id: UUID of the application.

        Returns:
            The matching ApplicationRecord.

        Raises:
            ApplicationNotFoundError: If no application with that ID exists.
        """

    @abstractmethod
    async def get_by_user(self, user_id: str) -> List[ApplicationRecord]:
        """Return all applications submitted by a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            List of ApplicationRecord instances.
        """

    @abstractmethod
    async def get_by_job(self, job_id: uuid.UUID) -> List[ApplicationRecord]:
        """Return all applications to a specific job.

        Args:
            job_id: UUID of the job.

        Returns:
            List of ApplicationRecord instances.
        """

    @abstractmethod
    async def has_user_applied_to_job(self, user_id: str, job_id: uuid.UUID) -> bool:
        """Check whether a user has already applied to a job.

        Args:
            user_id: Identifier of the user.
            job_id: UUID of the job.

        Returns:
            True if an application already exists for this user+job pair.
        """

    @abstractmethod
    async def get_applications_sent_today(self, user_id: str) -> List[ApplicationRecord]:
        """Return applications sent by a user in the last 24 hours.

        Args:
            user_id: Identifier of the user.

        Returns:
            List of ApplicationRecord instances sent within the last 24 hours.
        """

    @abstractmethod
    async def update_status(self, application_id: uuid.UUID, new_status: str) -> None:
        """Update the status of an application.

        Args:
            application_id: UUID of the application.
            new_status: New status string.
        """

    @abstractmethod
    async def update_reply_count(self, application_id: uuid.UUID, count: int) -> None:
        """Set the reply count for an application.

        Args:
            application_id: UUID of the application.
            count: New reply count value.
        """

    @abstractmethod
    async def count_by_user(self, user_id: str) -> int:
        """Count applications submitted by a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            Integer count of applications for that user.
        """
