"""Abstract base classes defining the registry interfaces."""

import uuid
from abc import ABC, abstractmethod
from typing import List, Optional

from shared.models.application_record import ApplicationRecord
from shared.models.job_record import JobRecord
from shared.models.variant_record import VariantRecord


class JobRegistryBase(ABC):
    """Interface for all JobRecord storage backends."""

    @abstractmethod
    async def save(self, jobs: List[JobRecord]) -> None:
        """Persist a list of job records.

        Args:
            jobs: List of JobRecord instances to save.
        """

    @abstractmethod
    async def get(self, job_id: uuid.UUID) -> JobRecord:
        """Retrieve a single job by ID.

        Args:
            job_id: UUID of the job to retrieve.

        Returns:
            The matching JobRecord.

        Raises:
            JobNotFoundError: If no job with that ID exists.
        """

    @abstractmethod
    async def get_many(self, job_ids: List[uuid.UUID]) -> List[JobRecord]:
        """Retrieve multiple jobs by their IDs.

        Args:
            job_ids: List of UUIDs to retrieve.

        Returns:
            List of matching JobRecord instances (missing IDs are skipped).
        """

    @abstractmethod
    async def get_all_with_email(self) -> List[JobRecord]:
        """Return all jobs that have a non-null apply_email.

        Returns:
            List of JobRecord instances with apply_email set.
        """

    @abstractmethod
    async def get_by_source(self, source: str) -> List[JobRecord]:
        """Return all jobs from a specific source platform.

        Args:
            source: One of "linkedin", "naukri", "indeed".

        Returns:
            List of matching JobRecord instances.
        """

    @abstractmethod
    async def get_by_status(self, status: str) -> List[JobRecord]:
        """Return all jobs with a specific status.

        Args:
            status: One of "raw", "reviewed", "applied", "closed".

        Returns:
            List of matching JobRecord instances.
        """

    @abstractmethod
    async def exists(self, job_id: uuid.UUID) -> bool:
        """Check whether a job exists without loading the full record.

        Args:
            job_id: UUID to check.

        Returns:
            True if the job exists, False otherwise.
        """

    @abstractmethod
    async def count(self) -> int:
        """Return the total number of stored jobs.

        Returns:
            Integer count of all job records.
        """

    @abstractmethod
    async def delete_by_source(self, source: str) -> int:
        """Delete all jobs from a specific source.

        Args:
            source: One of "linkedin", "naukri", "indeed".

        Returns:
            Number of records deleted.
        """


class VariantRegistryBase(ABC):
    """Interface for all VariantRecord storage backends."""

    @abstractmethod
    async def save(self, variant: VariantRecord) -> None:
        """Persist a new variant record.

        Args:
            variant: VariantRecord instance to save.
        """

    @abstractmethod
    async def get(self, variant_id: uuid.UUID) -> VariantRecord:
        """Retrieve a single variant by ID.

        Args:
            variant_id: UUID of the variant to retrieve.

        Returns:
            The matching VariantRecord.

        Raises:
            VariantNotFoundError: If no variant with that ID exists.
        """

    @abstractmethod
    async def get_for_job(self, job_id: uuid.UUID) -> List[VariantRecord]:
        """Return all variants generated for a specific job.

        Args:
            job_id: UUID of the job.

        Returns:
            List of VariantRecord instances for that job.
        """

    @abstractmethod
    async def get_approved_for_job(
        self, job_id: uuid.UUID, user_id: str
    ) -> Optional[VariantRecord]:
        """Return the approved variant for a user+job pair.

        Args:
            job_id: UUID of the job.
            user_id: Identifier of the user.

        Returns:
            The approved VariantRecord, or None if none exists.
        """

    @abstractmethod
    async def get_for_user(self, user_id: str) -> List[VariantRecord]:
        """Return all variants generated by a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            List of VariantRecord instances for that user.
        """

    @abstractmethod
    async def get_pending_for_user(self, user_id: str) -> List[VariantRecord]:
        """Return only pending variants awaiting approval for a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            List of pending VariantRecord instances.
        """

    @abstractmethod
    async def update_approval_status(self, variant_id: uuid.UUID, status: str) -> None:
        """Update the approval status of a variant.

        Args:
            variant_id: UUID of the variant to update.
            status: New status — "approved", "rejected", or "pending".
        """

    @abstractmethod
    async def update_approval_token(self, variant_id: uuid.UUID, token: str) -> None:
        """Store the email-based approval token for a variant.

        Args:
            variant_id: UUID of the variant.
            token: 64-character hex approval token.
        """

    @abstractmethod
    async def exists(self, variant_id: uuid.UUID) -> bool:
        """Check whether a variant exists.

        Args:
            variant_id: UUID to check.

        Returns:
            True if the variant exists, False otherwise.
        """

    @abstractmethod
    async def count_by_user(self, user_id: str) -> int:
        """Count variants generated by a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            Integer count of variants for that user.
        """


class ApplicationLogBase(ABC):
    """Interface for all ApplicationRecord storage backends."""

    @abstractmethod
    async def record_send(self, record: ApplicationRecord) -> None:
        """Log a new application send.

        Args:
            record: ApplicationRecord to persist.
        """

    @abstractmethod
    async def get(self, application_id: uuid.UUID) -> ApplicationRecord:
        """Retrieve an application by ID.

        Args:
            application_id: UUID of the application.

        Returns:
            The matching ApplicationRecord.

        Raises:
            ApplicationNotFoundError: If no application with that ID exists.
        """

    @abstractmethod
    async def get_by_user(self, user_id: str) -> List[ApplicationRecord]:
        """Return all applications submitted by a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            List of ApplicationRecord instances.
        """

    @abstractmethod
    async def get_by_job(self, job_id: uuid.UUID) -> List[ApplicationRecord]:
        """Return all applications to a specific job.

        Args:
            job_id: UUID of the job.

        Returns:
            List of ApplicationRecord instances.
        """

    @abstractmethod
    async def has_user_applied_to_job(self, user_id: str, job_id: uuid.UUID) -> bool:
        """Check whether a user has already applied to a job.

        Args:
            user_id: Identifier of the user.
            job_id: UUID of the job.

        Returns:
            True if an application already exists for this user+job pair.
        """

    @abstractmethod
    async def get_applications_sent_today(self, user_id: str) -> List[ApplicationRecord]:
        """Return applications sent by a user in the last 24 hours.

        Args:
            user_id: Identifier of the user.

        Returns:
            List of ApplicationRecord instances sent within the last 24 hours.
        """

    @abstractmethod
    async def update_status(self, application_id: uuid.UUID, new_status: str) -> None:
        """Update the status of an application.

        Args:
            application_id: UUID of the application.
            new_status: New status string.
        """

    @abstractmethod
    async def update_reply_count(self, application_id: uuid.UUID, count: int) -> None:
        """Set the reply count for an application.

        Args:
            application_id: UUID of the application.
            count: New reply count value.
        """

    @abstractmethod
    async def count_by_user(self, user_id: str) -> int:
        """Count applications submitted by a user.

        Args:
            user_id: Identifier of the user.

        Returns:
            Integer count of applications for that user.
        """


# ── Company & CareerJobs registry interfaces ──────────────────────────────────

from shared.models.company_record import CompanyRecord  # noqa: E402
from shared.models.career_job_record import CareerJobRecord  # noqa: E402
from typing import Dict, Set  # noqa: E402 — re-import for clarity in this section


class CompanyRegistryBase(ABC):
    """Interface for all CompanyRecord storage backends."""

    @abstractmethod
    async def save(self, company: CompanyRecord) -> None:
        """Persist a single company record (upsert on apex_domain).

        Args:
            company: CompanyRecord instance to save.
        """

    @abstractmethod
    async def save_many(self, companies: List[CompanyRecord]) -> None:
        """Persist a list of company records (upsert on apex_domain).

        Args:
            companies: List of CompanyRecord instances to save.
        """

    @abstractmethod
    async def get(self, company_id: uuid.UUID) -> CompanyRecord:
        """Retrieve a single company by UUID.

        Args:
            company_id: UUID of the company.

        Returns:
            The matching CompanyRecord.

        Raises:
            KeyError: If no company with that ID exists.
        """

    @abstractmethod
    async def get_by_apex_domain(self, apex_domain: str) -> Optional[CompanyRecord]:
        """Return the company record for a given apex domain, or None.

        Args:
            apex_domain: Normalised apex domain string (e.g. ``acme.com``).

        Returns:
            CompanyRecord if found, None otherwise.
        """

    @abstractmethod
    async def get_by_crawl_status(self, status: str) -> List[CompanyRecord]:
        """Return all companies with the given crawl_status.

        Args:
            status: One of ``pending``, ``enriched``, ``failed``,
                ``robots_blocked``, ``access_denied``, ``name_only``.

        Returns:
            List of matching CompanyRecord instances.
        """

    @abstractmethod
    async def get_pending_email_refresh(self, older_than_days: int = 30) -> List[CompanyRecord]:
        """Return enriched companies whose email data is stale.

        Args:
            older_than_days: Include companies not crawled for at least this
                many days (default 30).

        Returns:
            List of CompanyRecord instances due for email refresh.
        """

    @abstractmethod
    async def apex_domain_exists(self, apex_domain: str) -> bool:
        """Check whether an apex domain is already in the registry.

        Args:
            apex_domain: Normalised apex domain string.

        Returns:
            True if the domain exists, False otherwise.
        """

    @abstractmethod
    async def get_known_domains_set(self) -> Set[str]:
        """Return a set of all known apex domains for queue-level dedup.

        Returns:
            Set of apex domain strings currently in the registry.
        """

    @abstractmethod
    async def update_crawl_status(self, company_id: uuid.UUID, status: str) -> None:
        """Update the crawl_status of a company record.

        Args:
            company_id: UUID of the company.
            status: New crawl_status value.
        """

    @abstractmethod
    async def update_enrichment(self, company_id: uuid.UUID, **fields) -> None:
        """Partial-update enrichment fields on an existing company record.

        Only the provided keyword argument fields are updated.
        None values are ignored — they do not overwrite existing data.

        Args:
            company_id: UUID of the company to update.
            **fields: Field name/value pairs to update.
        """

    @abstractmethod
    async def count(self) -> int:
        """Return the total number of stored company records.

        Returns:
            Integer count of all companies.
        """

    @abstractmethod
    async def count_by_crawl_status(self) -> Dict[str, int]:
        """Return a breakdown of company counts by crawl_status.

        Returns:
            Dictionary mapping status string to count.
        """

    @abstractmethod
    async def count_by_ats_platform(self) -> Dict[str, int]:
        """Return a breakdown of company counts by detected ATS platform.

        Returns:
            Dictionary mapping ats_platform string to count.
        """


class CareerJobsRegistryBase(ABC):
    """Interface for all CareerJobRecord storage backends."""

    @abstractmethod
    async def save(self, job: CareerJobRecord) -> None:
        """Persist a single career job record (upsert on company_id + url_hash).

        Args:
            job: CareerJobRecord instance to save.
        """

    @abstractmethod
    async def save_many(self, jobs: List[CareerJobRecord]) -> None:
        """Persist a list of career job records (upsert on company_id + url_hash).

        Args:
            jobs: List of CareerJobRecord instances to save.
        """

    @abstractmethod
    async def get(self, career_job_id: uuid.UUID) -> CareerJobRecord:
        """Retrieve a single career job by UUID.

        Args:
            career_job_id: UUID of the career job.

        Returns:
            The matching CareerJobRecord.

        Raises:
            KeyError: If no record with that ID exists.
        """

    @abstractmethod
    async def get_by_company(self, company_id: uuid.UUID) -> List[CareerJobRecord]:
        """Return all career jobs for a given company.

        Args:
            company_id: UUID of the parent company.

        Returns:
            List of CareerJobRecord instances for that company.
        """

    @abstractmethod
    async def get_active(self, limit: int = 100, offset: int = 0) -> List[CareerJobRecord]:
        """Return active career jobs ordered by last_seen_at DESC.

        Args:
            limit: Maximum number of records to return.
            offset: Number of records to skip.

        Returns:
            List of active CareerJobRecord instances.
        """

    @abstractmethod
    async def url_hash_exists(self, company_id: uuid.UUID, url_hash: str) -> bool:
        """Check whether a (company_id, url_hash) pair already exists.

        Args:
            company_id: UUID of the parent company.
            url_hash: MD5 of the normalised job URL.

        Returns:
            True if the record exists, False otherwise.
        """

    @abstractmethod
    async def get_content_hash(
        self, company_id: uuid.UUID, url_hash: str
    ) -> Optional[str]:
        """Return the stored content_hash for a job without loading the full record.

        Args:
            company_id: UUID of the parent company.
            url_hash: MD5 of the normalised job URL.

        Returns:
            The stored content_hash string, or None if no record exists.
        """

    @abstractmethod
    async def update_last_seen(self, career_job_id: uuid.UUID) -> None:
        """Update last_seen_at to now for an unchanged job.

        Args:
            career_job_id: UUID of the career job.
        """

    @abstractmethod
    async def update_content(self, career_job_id: uuid.UUID, **fields) -> None:
        """Update content fields on a changed job record.

        Args:
            career_job_id: UUID of the career job to update.
            **fields: Field name/value pairs to update.
        """

    @abstractmethod
    async def mark_closed(self, career_job_id: uuid.UUID) -> None:
        """Set status to ``closed`` for a job no longer found on the career page.

        Args:
            career_job_id: UUID of the career job.
        """

    @abstractmethod
    async def mark_missing_jobs_closed(
        self, company_id: uuid.UUID, seen_url_hashes: Set[str]
    ) -> int:
        """After a crawl pass, close all jobs whose URL hash was not seen.

        Args:
            company_id: UUID of the company that was just crawled.
            seen_url_hashes: Set of url_hash values observed in the latest crawl.

        Returns:
            Number of records marked closed.
        """

    @abstractmethod
    async def count(self) -> int:
        """Return total number of career job records.

        Returns:
            Integer count.
        """

    @abstractmethod
    async def count_by_company(self, company_id: uuid.UUID) -> int:
        """Count career jobs for a specific company.

        Args:
            company_id: UUID of the company.

        Returns:
            Integer count.
        """

    @abstractmethod
    async def count_active_by_company(self) -> Dict[str, int]:
        """Return active job counts keyed by company_id string.

        Returns:
            Dictionary mapping company_id (str) to active job count.
        """
